"""
Operations — `02_DATABASE_DESIGN.md` §8.5: alerts, audit and messaging.
Generated by named server-side rules, never by the browser.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    ARRAY,
    ForeignKeyConstraint,
    Index,
    Integer,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import (
    Base,
    TenantMixin,
    UUIDPkMixin,
    enum_check,
    plain_fk,
    tenant_fk,
    uq_company_id,
)


class Alert(UUIDPkMixin, TenantMixin, Base):
    """Everything on the Alerts screen and the header badge."""

    __tablename__ = "alerts"

    rule_code: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    severity: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    category: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    reference_type: Mapped[Optional[str]] = mapped_column(Text, index=True)
    reference_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), index=True)
    reference_label: Mapped[Optional[str]] = mapped_column(Text)
    deep_link: Mapped[Optional[str]] = mapped_column(Text)
    godown_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), nullable=True, index=True)
    variance_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'new'"), index=True)
    auto_resolved: Mapped[bool] = mapped_column(nullable=False, server_default=text("false"))
    resolved_at: Mapped[Optional[datetime]] = mapped_column()
    resolved_by: Mapped[Optional[uuid.UUID]] = plain_fk("users.id", ondelete="SET NULL")
    dismissed_at: Mapped[Optional[datetime]] = mapped_column()
    dismissed_by: Mapped[Optional[uuid.UUID]] = plain_fk("users.id", ondelete="SET NULL")
    occurrence_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    last_occurred_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"), index=True)
    payload: Mapped[Optional[dict]] = mapped_column(JSONB)

    __table_args__ = (
        uq_company_id("alerts"),
        tenant_fk("alerts", "godown_id", "godowns", ondelete="SET NULL"),
        tenant_fk("alerts", "variance_id", "document_variances", ondelete="SET NULL"),
        # Dedupe rule BR-ALT-02, enforced at the database level.
        Index(
            "uq_alert_open",
            "company_id",
            "rule_code",
            "reference_type",
            "reference_id",
            unique=True,
            postgresql_where=text("status IN ('new','acknowledged')"),
        ),
        Index("ix_alerts_feed", "company_id", "status", "severity", "created_at"),
        enum_check("severity", ["critical", "high", "medium", "low"]),
        enum_check("category", ["Inventory", "Procurement", "Goods Receipt", "AI Documents", "System"]),
        enum_check(
            "reference_type",
            [
                "goods_receipt",
                "purchase_order",
                "product_variant",
                "document",
                "supplier_quotation",
                "proforma_invoice",
                "supplier_invoice",
                "company",
            ],
        ),
        enum_check("status", ["new", "acknowledged", "resolved", "dismissed"]),
    )
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))


class AlertRead(Base):
    """"Mark all as read" means *for me* — read state is per user."""

    __tablename__ = "alert_reads"

    alert_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True
    )
    read_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))

    __table_args__ = (
        tenant_fk("alert_reads", "alert_id", "alerts", ondelete="CASCADE"),
        # user_id kept a plain FK: users.company_id is nullable (platform
        # admins), so it cannot be the target of a composite tenant FK.
    )

    # company_id is needed for the composite FK above but is not itself part
    # of the (alert_id, user_id) PK.
    company_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False, index=True)


# alert_reads.user_id -> users.id is added as a plain FK via use_alter,
# matching the module's rule for references to a nullable-company_id table.
AlertRead.__table__.append_constraint(
    ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE", use_alter=True, name="fk_alert_reads_user_id_users")
)


class AlertRule(UUIDPkMixin, TenantMixin, Base):
    """(OPTIONAL) Makes thresholds tenant-editable instead of hardcoded."""

    __tablename__ = "alert_rules"

    rule_code: Mapped[str] = mapped_column(Text, nullable=False)
    is_enabled: Mapped[bool] = mapped_column(nullable=False, server_default=text("true"))
    severity_override: Mapped[Optional[str]] = mapped_column(Text)
    threshold_config: Mapped[Optional[dict]] = mapped_column(JSONB)
    schedule_cron: Mapped[Optional[str]] = mapped_column(Text)
    notify_email: Mapped[bool] = mapped_column(nullable=False, server_default=text("true"))
    notify_in_app: Mapped[bool] = mapped_column(nullable=False, server_default=text("true"))
    recipient_role_codes: Mapped[Optional[list[str]]] = mapped_column(ARRAY(Text))
    last_run_at: Mapped[Optional[datetime]] = mapped_column()
    last_run_status: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))

    __table_args__ = (
        uq_company_id("alert_rules"),
        UniqueConstraint("company_id", "rule_code", name="uq_alert_rule"),
    )


class AuditLog(Base):
    """The immutable record of who did what. PK is `(id, created_at)` so
    the table can be range-partitioned monthly later without a rewrite
    (§8.5 fn 1). Grants: INSERT and SELECT only — enforced by database role
    grants in a later infra phase, not by the ORM."""

    __tablename__ = "audit_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), server_default=text("gen_random_uuid()"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    company_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True, index=True
    )  # NULL for platform-level events; plain FK below via use_alter.
    entity_type: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), index=True)
    entity_label: Mapped[Optional[str]] = mapped_column(Text)
    action: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    description: Mapped[Optional[str]] = mapped_column(Text)
    actor_user_id: Mapped[Optional[uuid.UUID]] = plain_fk("users.id", ondelete="SET NULL", nullable=True)
    actor_name: Mapped[Optional[str]] = mapped_column(Text)
    actor_role: Mapped[Optional[str]] = mapped_column(Text)
    impersonated_by: Mapped[Optional[uuid.UUID]] = plain_fk("users.id", ondelete="SET NULL", nullable=True)
    before_data: Mapped[Optional[dict]] = mapped_column(JSONB)
    after_data: Mapped[Optional[dict]] = mapped_column(JSONB)
    changed_fields: Mapped[Optional[list]] = mapped_column(JSONB)
    ip_address: Mapped[Optional[str]] = mapped_column(INET)
    user_agent: Mapped[Optional[str]] = mapped_column(Text)
    request_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    source: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'api'"))

    __table_args__ = (
        PrimaryKeyConstraint("id", "created_at", name="pk_audit_logs"),
        Index("ix_audit_logs_entity", "company_id", "entity_type", "entity_id", "created_at"),
        Index("ix_audit_logs_actor", "company_id", "actor_user_id", "created_at"),
        enum_check(
            "entity_type",
            [
                "purchase_order",
                "rfq",
                "goods_receipt",
                "supplier_quotation",
                "proforma_invoice",
                "supplier_invoice",
                "product",
                "product_variant",
                "supplier",
                "inventory_transaction",
                "user",
                "invitation",
                "company",
                "document",
                "ai_extraction",
                "alert",
                "settings",
                # Added in migration efc6b3fb9fdb: 06_BUSINESS_RULES.md §15
                # requires master-data changes to be audited, and these
                # master tables had no entity_type. `permission` covers
                # denial rows, which describe an attempted action rather
                # than a row in any table.
                "godown",
                "category",
                "brand",
                "uom",
                "permission",
                "purchase_return",
                "stock_transfer",
                "role",
                "quotation_comparison",
                "supplier_portal_access",
                # Added in migration c7e2a9f4b1d3.
                "company_list",
                "subscription_plan",
            ],
        ),
        enum_check(
            "action",
            [
                "created",
                "updated",
                "deleted",
                "status_changed",
                "approved",
                "rejected",
                "sent",
                "confirmed",
                "cancelled",
                "logged_in",
                "logged_out",
                "impersonated",
                "exported",
                "invited",
                "invitation_resent",
                "invitation_revoked",
                "invitation_accepted",
                "removed",
                "suspended",
                "reactivated",
                # Added in migration efc6b3fb9fdb — §15 mandates auditing
                # login failures, password changes/resets and "every
                # permission denial", none of which had an action value.
                "login_failed",
                "permission_denied",
                "password_changed",
                "password_reset",
            ],
        ),
        enum_check("source", ["api", "job", "system", "import"]),
    )


AuditLog.__table__.append_constraint(
    ForeignKeyConstraint(
        ["company_id"], ["companies.id"], ondelete="RESTRICT", use_alter=True, name="fk_audit_logs_company_id_companies"
    )
)


class OutboundMessage(UUIDPkMixin, TenantMixin, Base):
    """Proof of what was actually sent when the UI says "the supplier has
    been emailed a copy"."""

    __tablename__ = "outbound_messages"

    channel: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'email'"), index=True)
    message_type: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    related_type: Mapped[Optional[str]] = mapped_column(Text, index=True)
    related_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), index=True)
    supplier_id: Mapped[Optional[uuid.UUID]] = mapped_column(PGUUID(as_uuid=True), nullable=True, index=True)
    to_address: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    cc_addresses: Mapped[Optional[list[str]]] = mapped_column(ARRAY(Text))
    subject: Mapped[Optional[str]] = mapped_column(Text)
    body_preview: Mapped[Optional[str]] = mapped_column(Text)
    attachment_document_ids: Mapped[Optional[list[uuid.UUID]]] = mapped_column(ARRAY(PGUUID(as_uuid=True)))
    provider: Mapped[Optional[str]] = mapped_column(Text)
    provider_message_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'queued'"), index=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    queued_at: Mapped[Optional[datetime]] = mapped_column()
    sent_at: Mapped[Optional[datetime]] = mapped_column()
    delivered_at: Mapped[Optional[datetime]] = mapped_column()
    sent_by: Mapped[Optional[uuid.UUID]] = plain_fk("users.id", ondelete="SET NULL")

    __table_args__ = (
        uq_company_id("outbound_messages"),
        tenant_fk("outbound_messages", "supplier_id", "suppliers", ondelete="SET NULL"),
        enum_check("channel", ["email", "whatsapp", "sms"]),
        enum_check(
            "message_type",
            ["rfq", "purchase_order", "proforma_query", "invitation", "alert_digest", "password_reset", "purchase_return"],
        ),
        enum_check(
            "related_type",
            ["rfq", "purchase_order", "proforma_invoice", "supplier_quotation", "invitation", "purchase_return"],
        ),
        enum_check("status", ["queued", "sent", "delivered", "bounced", "complained", "failed"]),
    )


class NotificationPreference(Base):
    """(OPTIONAL) Per-user overrides of the company defaults."""

    __tablename__ = "notification_preferences"

    user_id: Mapped[uuid.UUID] = plain_fk("users.id", ondelete="CASCADE", nullable=False)
    notification_type: Mapped[str] = mapped_column(Text, nullable=False)
    in_app: Mapped[bool] = mapped_column(nullable=False, server_default=text("true"))
    email: Mapped[bool] = mapped_column(nullable=False, server_default=text("true"))
    digest_frequency: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'immediate'"))

    __table_args__ = (
        PrimaryKeyConstraint("user_id", "notification_type", name="pk_notification_preferences"),
        enum_check("digest_frequency", ["immediate", "daily", "weekly", "never"]),
    )
