/**
 * The procurement chain: RFQ → Quotation → Comparison → PO → Proforma → GRN
 * → Supplier Invoice, plus Purchase Returns and cross-document variances.
 *
 * Every link is an id. Document numbers (`PO-2026-00123`) are for humans to
 * read; relationships never depend on them (C12).
 */

import type {
  DateOnly,
  Id,
  MatchMethod,
  Money,
  Percent,
  Provenance,
  Quantity,
  Timestamp,
} from "./common";

/* ------------------------------------------------------------------ RFQ */

export type RfqStatus =
  | "draft"
  | "sent"
  | "partially_quoted"
  | "quoted"
  | "closed"
  | "cancelled";

export interface Rfq {
  id: Id;
  rfqNumber: string;
  rfqDate: DateOnly;
  expectedDeliveryDate: DateOnly | null;
  subject: string;
  deliveryGodownId: Id | null;
  notes: string;
  status: RfqStatus;
  sentAt?: Timestamp | null;
  closedAt?: Timestamp | null;
  estimatedValue: Money;
  createdFrom: "manual" | "low_stock" | "imported";
  createdAt: Timestamp;
  rowVersion: number;
  /** Set only when createdFrom === "imported" (BR-RFQ-09). */
  externalSourceName?: string | null;
  externalReferenceNumber?: string | null;
  sourceFileName?: string | null;
}

export interface RfqItem {
  id: Id;
  rfqId: Id;
  lineNo: number;
  /** Nullable: a buyer may request something not yet in the catalogue. */
  productVariantId: Id | null;
  description: string;
  quantity: Quantity;
  uomId: Id;
  expectedPrice: Money;
  remarks?: string;
}

export type RfqSupplierStatus = "pending" | "sent" | "failed" | "viewed" | "quoted" | "declined";

export interface RfqSupplier {
  id: Id;
  rfqId: Id;
  supplierId: Id;
  status: RfqSupplierStatus;
  sentAt?: Timestamp | null;
  respondedAt?: Timestamp | null;
  declineReason?: string;
}

/* ----------------------------------------------------------- Quotation */

export type QuotationStatus =
  | "draft"
  | "under_review"
  | "approved"
  | "rejected"
  | "expired"
  | "superseded"
  | "converted";

export type QuotationSource = "ai_extracted" | "manual" | "email" | "portal";

export interface SupplierQuotation {
  id: Id;
  /** The supplier's own number, captured — never generated by us. */
  quotationNumber: string;
  supplierId: Id;
  rfqId: Id | null;
  quotationDate: DateOnly;
  validUntil: DateOnly | null;
  currencyCode: string;

  subtotal: Money;
  discountAmount: Money;
  taxableValue: Money;
  taxAmount: Money;
  freightAmount: Money;
  otherCharges: Money;
  roundOff: Money;
  totalAmount: Money;

  paymentTerms: string;
  deliveryTerms: string;
  deliveryPeriodDays: number | null;
  warrantyTerms: string;
  freightTerms: string;

  source: QuotationSource;
  documentId: Id | null;
  aiExtractionResultId: Id | null;
  extractionConfidence: Percent | null;

  status: QuotationStatus;
  approvedBy?: Id | null;
  approvedAt?: Timestamp | null;
  rejectedReason?: string;
  createdAt: Timestamp;
  rowVersion: number;
}

export interface SupplierQuotationItem {
  id: Id;
  quotationId: Id;
  lineNo: number;
  rfqItemId: Id | null;
  productVariantId: Id | null;
  rawDescription: string;
  supplierSku?: string;
  quantity: Quantity;
  uomId: Id;
  unitPrice: Money;
  discountPct: Percent;
  gstRate: Percent;
  cessRate: Percent;
  lineNet: Money;
  lineTax: Money;
  lineTotal: Money;
  isAvailable: boolean;
  availabilityNote?: string;
  leadTimeDays?: number;
  matchConfidence?: Percent;
  matchMethod?: MatchMethod;
  provenance: Provenance;
}

/* ---------------------------------------------------------- Comparison */

export type ComparisonStatus = "draft" | "decided" | "converted" | "discarded";
export type ComparisonStrategy = "lowest_price" | "split_optimal" | "manual";

export interface QuotationComparison {
  id: Id;
  rfqId: Id;
  name: string;
  comparedSupplierIds: Id[];
  strategy: ComparisonStrategy;
  singleSupplierBestSupplierId: Id | null;
  singleSupplierBestTotal: Money;
  splitTotal: Money;
  projectedSavings: Money;
  decidedBy?: Id | null;
  decidedAt?: Timestamp | null;
  status: ComparisonStatus;
  notes?: string;
  createdAt: Timestamp;
}

export interface QuotationComparisonLine {
  id: Id;
  comparisonId: Id;
  rfqItemId: Id;
  productVariantId: Id | null;
  description: string;
  quantity: Quantity;
  uomId: Id;
  selectedQuotationItemId: Id | null;
  selectedSupplierId: Id | null;
  recommendedQuotationItemId: Id | null;
  recommendedSupplierId: Id | null;
  /** Computed by the recommendation service, never hardcoded (I5). */
  recommendationReason: string;
  recommendationScore: number;
  priceSpreadPct: Percent;
  overrideReason?: string;
}

/** A comparison rendered for the screen: matrix cells + commercial terms. */
export interface ComparisonCell {
  supplierId: Id;
  supplierName: string;
  quotationId: Id;
  quotationItemId: Id;
  unitPrice: Money;
  lineTotal: Money;
  gstRate: Percent;
  isAvailable: boolean;
  note?: string;
  isLowest: boolean;
}

export interface ComparisonRowView {
  rfqItemId: Id;
  productVariantId: Id | null;
  sku: string;
  productName: string;
  quantity: Quantity;
  uomCode: string;
  cells: ComparisonCell[];
  recommendedSupplierId: Id | null;
  recommendationReason: string;
  recommendationScore: number;
  priceSpreadPct: Percent;
}

export interface CommercialTermRow {
  label: string;
  values: Record<Id, string>;
  bestSupplierId?: Id;
}

export interface ComparisonView {
  comparison: QuotationComparison;
  suppliers: {
    supplierId: Id;
    name: string;
    quotationId: Id;
    quotationNumber: string;
    validUntil: DateOnly | null;
    isExpired: boolean;
    total: Money;
    missingLines: number;
  }[];
  rows: ComparisonRowView[];
  lines: QuotationComparisonLine[];
  terms: CommercialTermRow[];
  totals: {
    lowestSingleSupplierId: Id | null;
    lowestSingleSupplierTotal: Money;
    splitTotal: Money;
    projectedSavings: Money;
  };
  warnings: { code: string; message: string; rfqItemId?: Id; supplierId?: Id }[];
}

/* ----------------------------------------------------- Purchase Order */

export type PurchaseOrderStatus =
  | "draft"
  | "pending_approval"
  | "approved"
  | "sent"
  | "acknowledged"
  | "partially_received"
  | "received"
  | "closed"
  | "cancelled";

export type PoLineStatus = "open" | "partially_received" | "received" | "short_closed" | "cancelled";

export interface PurchaseOrder {
  id: Id;
  poNumber: string;
  supplierId: Id;
  rfqId: Id | null;
  quotationId: Id | null;
  comparisonId: Id | null;
  poDate: DateOnly;
  expectedDeliveryDate: DateOnly | null;
  deliveryGodownId: Id;
  paymentTerms: string;
  deliveryTerms: string;
  /** Copied from the delivery godown's state at creation. */
  placeOfSupplyStateCode: string;
  /** Derived from supplier state vs place of supply — never hardcoded (C14). */
  isInterState: boolean;
  currencyCode: string;

  subtotal: Money;
  discountAmount: Money;
  taxableValue: Money;
  cgstAmount: Money;
  sgstAmount: Money;
  igstAmount: Money;
  cessAmount: Money;
  freightAmount: Money;
  otherCharges: Money;
  roundOff: Money;
  totalAmount: Money;

  status: PurchaseOrderStatus;
  approvedBy?: Id | null;
  approvedAt?: Timestamp | null;
  sentAt?: Timestamp | null;
  cancelledAt?: Timestamp | null;
  cancelledBy?: Id | null;
  cancellationReason?: string;
  /** Derived from line receipts — never set by hand (BR-PO-05). */
  receivedPct: Percent;
  fullyReceivedAt?: Timestamp | null;
  notes?: string;
  createdAt: Timestamp;
  rowVersion: number;
}

export interface PurchaseOrderItem {
  id: Id;
  purchaseOrderId: Id;
  lineNo: number;
  productVariantId: Id;
  quotationItemId: Id | null;
  rfqItemId: Id | null;
  description: string;
  hsnCode: string;
  quantity: Quantity;
  uomId: Id;
  conversionFactor: number;
  unitPrice: Money;
  discountPct: Percent;
  gstRate: Percent;
  cessRate: Percent;
  lineNet: Money;
  lineTax: Money;
  lineTotal: Money;
  /** Σ accepted quantity across confirmed GRNs (C10). */
  receivedQuantity: Quantity;
  returnedQuantity: Quantity;
  invoicedQuantity: Quantity;
  lineStatus: PoLineStatus;
  expectedDeliveryDate?: DateOnly | null;
}

/** A PO line prepared for receiving — pending balance, not original quantity. */
export interface ReceiptLine {
  purchaseOrderItemId: Id;
  productVariantId: Id;
  sku: string;
  productName: string;
  uomId: Id;
  uomCode: string;
  unitPrice: Money;
  gstRate: Percent;
  orderedQuantity: Quantity;
  previouslyReceivedQuantity: Quantity;
  pendingQuantity: Quantity;
  suggestedReceivedQuantity: Quantity;
  requiresBatch: boolean;
  lineStatus: PoLineStatus;
}

/* --------------------------------------------------------- Proforma */

export type ProformaStatus =
  | "pending"
  | "under_review"
  | "approved"
  | "rejected"
  | "paid"
  | "completed"
  | "cancelled";

export interface ProformaInvoice {
  id: Id;
  proformaNumber: string;
  supplierId: Id;
  purchaseOrderId: Id | null;
  proformaDate: DateOnly;
  validUntil?: DateOnly | null;
  placeOfSupplyStateCode: string;
  isInterState: boolean;

  subtotal: Money;
  discountAmount: Money;
  taxableValue: Money;
  cgstAmount: Money;
  sgstAmount: Money;
  igstAmount: Money;
  cessAmount: Money;
  freightAmount: Money;
  otherCharges: Money;
  roundOff: Money;
  totalAmount: Money;

  /** The PO total at the moment the documents were linked. */
  poTotalSnapshot: Money;
  varianceAmount: Money;
  advancePercent?: Percent | null;
  advanceAmount?: Money | null;
  paymentInstructions: string;
  bankName?: string;
  bankAccountNo?: string;
  bankIfsc?: string;
  supplierGstinSnapshot: string | null;
  supplierAddressSnapshot: string;
  documentId: Id | null;
  aiExtractionResultId: Id | null;
  status: ProformaStatus;
  approvedBy?: Id | null;
  approvedAt?: Timestamp | null;
  queryRaisedAt?: Timestamp | null;
  queryNote?: string;
  createdAt: Timestamp;
}

export interface ProformaInvoiceItem {
  id: Id;
  proformaId: Id;
  lineNo: number;
  purchaseOrderItemId: Id | null;
  productVariantId: Id | null;
  description: string;
  hsnCode: string;
  quantity: Quantity;
  uomId: Id;
  unitPrice: Money;
  gstRate: Percent;
  cessRate: Percent;
  lineNet: Money;
  lineTax: Money;
  lineTotal: Money;
  /** The PO rate, frozen — what the variance was reviewed against. */
  poUnitPriceSnapshot?: Money | null;
  priceVariancePct?: Percent | null;
}

/* ------------------------------------------------------ Goods Receipt */

export type GoodsReceiptStatus =
  | "draft"
  | "partially_received"
  | "received"
  | "cancelled"
  | "reversed";

export type GrnIssueType =
  | "none"
  | "short"
  | "excess"
  | "damaged"
  | "expired"
  | "wrong_product"
  | "wrong_variant"
  | "wrong_model"
  | "wrong_brand";

export interface GoodsReceipt {
  id: Id;
  grnNumber: string;
  grnDate: DateOnly;
  supplierId: Id;
  purchaseOrderId: Id | null;
  godownId: Id;
  receivedByUserId: Id;
  vehicleNumber: string;
  transporterName: string;
  lrNumber: string;
  ewayBillNumber: string;
  supplierChallanNumber: string;
  supplierChallanDate: DateOnly | null;
  status: GoodsReceiptStatus;
  confirmedBy?: Id | null;
  confirmedAt?: Timestamp | null;
  cancelledAt?: Timestamp | null;
  cancellationReason?: string;
  /** Set on the original when a reversing GRN is raised (C6). */
  reversedByGrnId?: Id | null;
  /** Set on the reversing GRN, pointing back at what it reverses. */
  reversalOfGrnId?: Id | null;
  hasDiscrepancy: boolean;
  remarks: string;
  createdAt: Timestamp;
  rowVersion: number;
}

export interface GoodsReceiptItem {
  id: Id;
  goodsReceiptId: Id;
  lineNo: number;
  /** The link that makes partial receipt computable (C10). */
  purchaseOrderItemId: Id | null;
  productVariantId: Id;
  batchId: Id | null;
  batchNumber?: string;
  manufacturedOn?: DateOnly | null;
  expiresOn?: DateOnly | null;
  orderedQuantity: Quantity;
  previouslyReceivedQuantity: Quantity;
  receivedQuantity: Quantity;
  acceptedQuantity: Quantity;
  /** Derived: received − accepted. */
  rejectedQuantity: Quantity;
  uomId: Id;
  conversionFactor: number;
  unitPrice: Money;
  issueType: GrnIssueType;
  expectedVariantId?: Id | null;
  rejectionReason?: string;
  remarks: string;
  /** Proof that stock was posted for this line. */
  inventoryTransactionId?: Id | null;
}

/** What `confirmGoodsReceipt` returns — the whole downstream effect (C1). */
export interface GrnConfirmationResult {
  goodsReceipt: GoodsReceipt;
  postings: {
    goodsReceiptItemId: Id;
    inventoryTransactionId: Id;
    productVariantId: Id;
    sku: string;
    godownId: Id;
    quantity: Quantity;
    balanceAfter: Quantity;
  }[];
  purchaseOrder: { id: Id; poNumber: string; receivedPct: Percent; status: PurchaseOrderStatus } | null;
  variances: DocumentVariance[];
  alertIds: Id[];
}

/* ---------------------------------------------------- Supplier Invoice */

export type SupplierInvoiceStatus = "draft" | "under_review" | "approved" | "disputed" | "cancelled";
export type InvoiceMatchStatus = "unmatched" | "matched" | "variance";
export type InvoicePaymentStatus = "unpaid" | "partially_paid" | "paid";
export type InvoiceType = "tax_invoice" | "bill_of_supply" | "debit_note" | "credit_note";

export interface SupplierInvoice {
  id: Id;
  /** The supplier's number, captured. */
  invoiceNumber: string;
  invoiceDate: DateOnly;
  supplierId: Id;
  purchaseOrderId: Id | null;
  goodsReceiptId: Id | null;
  supplierGstin: string | null;
  buyerGstin: string | null;
  placeOfSupplyStateCode: string;
  isInterState: boolean;
  invoiceType: InvoiceType;

  subtotal: Money;
  discountAmount: Money;
  taxableValue: Money;
  cgstAmount: Money;
  sgstAmount: Money;
  igstAmount: Money;
  cessAmount: Money;
  freightAmount: Money;
  otherCharges: Money;
  roundOff: Money;
  totalAmount: Money;
  tdsAmount: Money;

  ewayBillNumber: string;
  irn?: string;
  dueDate: DateOnly | null;
  amountPaid: Money;
  paymentStatus: InvoicePaymentStatus;
  matchStatus: InvoiceMatchStatus;
  varianceAmount: Money;
  documentId: Id | null;
  aiExtractionResultId: Id | null;
  status: SupplierInvoiceStatus;
  approvedBy?: Id | null;
  approvedAt?: Timestamp | null;
  disputeReason?: string;
  notes?: string;
  createdAt: Timestamp;
  rowVersion: number;
}

export interface SupplierInvoiceItem {
  id: Id;
  invoiceId: Id;
  lineNo: number;
  purchaseOrderItemId: Id | null;
  goodsReceiptItemId: Id | null;
  productVariantId: Id | null;
  description: string;
  hsnCode: string;
  quantity: Quantity;
  uomId: Id;
  unitPrice: Money;
  discountPct: Percent;
  gstRate: Percent;
  cessRate: Percent;
  lineNet: Money;
  lineTax: Money;
  lineTotal: Money;
  poUnitPriceSnapshot?: Money | null;
  grnAcceptedQuantity?: Quantity | null;
  priceVariancePct?: Percent | null;
  qtyVariance?: Quantity | null;
}

/** The three-way match result. */
export interface ThreeWayMatch {
  invoiceId: Id;
  matchStatus: InvoiceMatchStatus;
  summary: { poTotal: Money; grnValue: Money; invoiceTotal: Money };
  variances: DocumentVariance[];
}

/* ------------------------------------------------------ Purchase Return */

export type PurchaseReturnStatus = "draft" | "sent" | "accepted" | "credited" | "cancelled";

export type ReturnReason =
  | "damaged"
  | "expired"
  | "wrong_product"
  | "wrong_variant"
  | "quality_rejected"
  | "excess_supply"
  | "other";

export interface PurchaseReturn {
  id: Id;
  returnNumber: string;
  returnDate: DateOnly;
  supplierId: Id;
  goodsReceiptId: Id;
  purchaseOrderId: Id | null;
  godownId: Id;
  reason: ReturnReason;
  status: PurchaseReturnStatus;
  debitNoteNumber?: string;
  totalAmount: Money;
  ewayBillNumber?: string;
  remarks?: string;
  confirmedBy?: Id | null;
  confirmedAt?: Timestamp | null;
  createdAt: Timestamp;
}

export interface PurchaseReturnItem {
  id: Id;
  returnId: Id;
  goodsReceiptItemId: Id;
  productVariantId: Id;
  batchId: Id | null;
  quantity: Quantity;
  uomId: Id;
  unitPrice: Money;
  gstRate: Percent;
  lineTotal: Money;
  reason: ReturnReason;
  remarks?: string;
  inventoryTransactionId?: Id | null;
}

/* ------------------------------------------------------- Variances */

export type VarianceType = "price" | "quantity" | "tax" | "total" | "product" | "delivery_date";
export type ComparisonKind =
  | "proforma_vs_po"
  | "grn_vs_po"
  | "invoice_vs_po"
  | "invoice_vs_grn";
export type VarianceSeverity = "info" | "warning" | "critical";
export type VarianceStatus = "open" | "accepted" | "disputed" | "resolved";

export interface DocumentVariance {
  id: Id;
  varianceType: VarianceType;
  comparisonKind: ComparisonKind;
  baseDocType: string;
  baseDocId: Id;
  baseLineId?: Id | null;
  compareDocType: string;
  compareDocId: Id;
  compareLineId?: Id | null;
  productVariantId?: Id | null;
  label: string;
  baseValue: number;
  compareValue: number;
  difference: number;
  differencePct: Percent;
  severity: VarianceSeverity;
  status: VarianceStatus;
  resolvedBy?: Id | null;
  resolvedAt?: Timestamp | null;
  resolutionNote?: string;
  alertId?: Id | null;
}
