"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, Plus, Save, Trash2 } from "lucide-react";

import { FormError } from "@/components/common/async-state";
import { SectionCard } from "@/components/common/section-card";
import { RfqLinkField } from "@/components/procurement/rfq-link-field";
import { TaxSummary } from "@/components/procurement/tax-summary";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useProducts, useUoms } from "@/hooks/use-catalog";
import { useCreateQuotation, useRfq } from "@/hooks/use-procurement";
import { useSuppliers } from "@/hooks/use-suppliers";
import { computeDocumentTotals, computeLine, formatMoney, taxBreakdown } from "@/lib/domain/money";
import type { Id } from "@/types";

interface LineRow {
  key: string;
  rfqItemId: Id | null;
  productVariantId: Id | "";
  supplierSku: string;
  quantity: number;
  uomId: Id | "";
  unitPrice: number;
  discountPct: number;
  gstRate: number;
  isAvailable: boolean;
  availabilityNote: string;
}

// `key` is generated by the caller, from a counter scoped to the component
// instance (a ref) rather than module scope — a module-level counter keeps
// incrementing across every request the long-lived Next dev/prod server
// renders, while a fresh client bundle load always starts at 1, so SSR and
// the client would hand out different keys/ids for what's otherwise an
// identical first render (a React hydration-mismatch bug, since these keys
// also become DOM ids via `avail-${line.key}`). A ref reset per mount keeps
// server and client in sync.
function blankLine(key: string): LineRow {
  return {
    key,
    rfqItemId: null,
    productVariantId: "",
    supplierSku: "",
    quantity: 1,
    uomId: "",
    unitPrice: 0,
    discountPct: 0,
    gstRate: 18,
    isAvailable: true,
    availabilityNote: "",
  };
}

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Manual quotation entry — the path for a quote that arrived by phone or on
 * paper. We never generate the quotation number here; it is the supplier's
 * own, typed in as given (I3).
 */
export function QuotationForm() {
  const router = useRouter();

  const productsState = useProducts({ limit: 500, sort: "name" });
  const uomsState = useUoms();
  const suppliersState = useSuppliers({ limit: 200 });

  const products = productsState.data?.items ?? [];
  const uoms = uomsState.data ?? [];
  const suppliers = (suppliersState.data?.items ?? []).filter((s) => s.status === "active");

  const [quotationNumber, setQuotationNumber] = React.useState("");
  const [supplierId, setSupplierId] = React.useState<Id | "">("");
  const [rfqId, setRfqId] = React.useState<Id | null>(null);
  const [quotationDate, setQuotationDate] = React.useState(todayIso());
  const [validUntil, setValidUntil] = React.useState("");
  const [paymentTerms, setPaymentTerms] = React.useState("");
  const [deliveryTerms, setDeliveryTerms] = React.useState("");
  const [deliveryPeriodDays, setDeliveryPeriodDays] = React.useState("");
  const [warrantyTerms, setWarrantyTerms] = React.useState("");
  const [freightTerms, setFreightTerms] = React.useState("");
  const [freightAmount, setFreightAmount] = React.useState(0);
  const [otherCharges, setOtherCharges] = React.useState(0);
  const nextRowKeyRef = React.useRef(1);
  const nextRowKey = React.useCallback(() => `l${nextRowKeyRef.current++}`, []);
  const [lines, setLines] = React.useState<LineRow[]>(() => [blankLine(nextRowKey())]);

  const rfqState = useRfq(rfqId ?? undefined);

  const create = useCreateQuotation((quotation) => router.push(`/procurement/quotations/${quotation.id}`));

  function updateLine(key: string, patch: Partial<LineRow>) {
    setLines((prev) => prev.map((l) => (l.key === key ? { ...l, ...patch } : l)));
  }

  function handleProductChange(key: string, productVariantId: Id) {
    const product = products.find((p) => p.id === productVariantId);
    const uom = uoms.find((u) => u.code === product?.uomCode);
    updateLine(key, {
      productVariantId,
      uomId: uom?.id ?? "",
      unitPrice: product?.purchasePrice ?? 0,
      gstRate: product?.gstRate ?? 18,
    });
  }

  function addLine() {
    setLines((prev) => [...prev, blankLine(nextRowKey())]);
  }

  // Pull in the RFQ's own items the first time a buyer links one, so the
  // quotation lines match what was actually asked for.
  React.useEffect(() => {
    const data = rfqState.data;
    if (!rfqId || !data) return;
    setLines((current) => {
      if (current.some((l) => l.productVariantId)) return current;
      const fromRfq = data.items
        .filter((item) => item.productVariantId)
        .map((item) => ({
          key: nextRowKey(),
          rfqItemId: item.id,
          productVariantId: item.productVariantId as Id,
          supplierSku: "",
          quantity: item.quantity,
          uomId: item.uomId,
          unitPrice: item.expectedPrice,
          discountPct: 0,
          gstRate: products.find((p) => p.id === item.productVariantId)?.gstRate ?? 18,
          isAvailable: true,
          availabilityNote: "",
        }));
      return fromRfq.length ? fromRfq : current;
    });
    // products is intentionally omitted — it's stable list data, not a trigger for this effect.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rfqId, rfqState.data]);

  const taxableLines = lines
    .filter((l) => l.isAvailable && l.productVariantId)
    .map((l) => ({
      quantity: l.quantity,
      unitPrice: l.unitPrice,
      discountPct: l.discountPct,
      gstRate: l.gstRate,
      cessRate: 0,
    }));

  const totals = computeDocumentTotals({
    lines: taxableLines,
    freightAmount,
    otherCharges,
    forceInterState: false,
  });
  const taxRows = taxBreakdown(taxableLines, false);

  function fieldError(index: number, field: string): string | undefined {
    return create.fieldErrors[`lines.${index}.${field}`];
  }

  function submit() {
    create.run({
      quotationNumber: quotationNumber.trim(),
      supplierId: supplierId as Id,
      rfqId,
      quotationDate,
      validUntil: validUntil || null,
      paymentTerms,
      deliveryTerms,
      deliveryPeriodDays: deliveryPeriodDays ? Number(deliveryPeriodDays) : null,
      warrantyTerms,
      freightTerms,
      freightAmount,
      otherCharges,
      lines: lines
        .filter((l) => l.productVariantId)
        .map((l) => ({
          productVariantId: l.productVariantId as Id,
          quantity: l.quantity,
          uomId: l.uomId as Id,
          unitPrice: l.unitPrice,
          discountPct: l.discountPct,
          gstRate: l.gstRate,
          rfqItemId: l.rfqItemId,
          supplierSku: l.supplierSku || undefined,
          isAvailable: l.isAvailable,
          availabilityNote: l.isAvailable ? undefined : l.availabilityNote || undefined,
        })),
      source: "manual",
    });
  }

  return (
    <div className="space-y-4">
      <FormError message={create.error} fieldErrors={create.fieldErrors} />

      <SectionCard
        title="Quotation Details"
        description="Enter this the way the supplier sent it — we never generate their number"
      >
        <div className="grid grid-cols-1 gap-4 p-4 sm:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-1.5">
            <Label htmlFor="qf-number">Supplier&apos;s Quotation Number</Label>
            <Input
              id="qf-number"
              value={quotationNumber}
              onChange={(e) => setQuotationNumber(e.target.value)}
              placeholder="e.g. QT/2026/4521"
            />
            {create.fieldErrors.quotationNumber && (
              <p className="text-[12px] text-destructive">{create.fieldErrors.quotationNumber}</p>
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-supplier">Supplier</Label>
            <Select value={supplierId} onValueChange={(v) => setSupplierId(v)}>
              <SelectTrigger id="qf-supplier">
                <SelectValue placeholder="Select supplier" />
              </SelectTrigger>
              <SelectContent>
                {suppliers.map((s) => (
                  <SelectItem key={s.id} value={s.id}>
                    {s.name} · {s.city}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {create.fieldErrors.supplierId && (
              <p className="text-[12px] text-destructive">{create.fieldErrors.supplierId}</p>
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-date">Quotation Date</Label>
            <div className="relative">
              <Input
                id="qf-date"
                type="date"
                value={quotationDate}
                onChange={(e) => setQuotationDate(e.target.value)}
                className="pr-9"
              />
              <CalendarDays className="pointer-events-none absolute top-1/2 right-3 size-4 -translate-y-1/2 text-muted-foreground" />
            </div>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-valid">Valid Until</Label>
            <div className="relative">
              <Input
                id="qf-valid"
                type="date"
                value={validUntil}
                onChange={(e) => setValidUntil(e.target.value)}
                className="pr-9"
              />
              <CalendarDays className="pointer-events-none absolute top-1/2 right-3 size-4 -translate-y-1/2 text-muted-foreground" />
            </div>
            {create.fieldErrors.validUntil && (
              <p className="text-[12px] text-destructive">{create.fieldErrors.validUntil}</p>
            )}
          </div>

          <div className="sm:col-span-2 lg:col-span-2">
            <RfqLinkField value={rfqId} onChange={setRfqId} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-payment">Payment Terms</Label>
            <Input id="qf-payment" value={paymentTerms} onChange={(e) => setPaymentTerms(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-delivery-terms">Delivery Terms</Label>
            <Input id="qf-delivery-terms" value={deliveryTerms} onChange={(e) => setDeliveryTerms(e.target.value)} />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="qf-delivery-days">Delivery Period (days)</Label>
            <Input
              id="qf-delivery-days"
              type="number"
              min={0}
              value={deliveryPeriodDays}
              onChange={(e) => setDeliveryPeriodDays(e.target.value)}
              className="tabular"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-warranty">Warranty Terms</Label>
            <Input id="qf-warranty" value={warrantyTerms} onChange={(e) => setWarrantyTerms(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="qf-freight-terms">Freight Terms</Label>
            <Input id="qf-freight-terms" value={freightTerms} onChange={(e) => setFreightTerms(e.target.value)} />
          </div>
        </div>
      </SectionCard>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-12">
        <div className="xl:col-span-8">
          <SectionCard
            title="Items"
            action={
              <Button variant="outline" size="sm" onClick={addLine}>
                <Plus />
                Add Item
              </Button>
            }
          >
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead className="pl-4">Product</TableHead>
                  <TableHead className="w-20 text-right">Qty</TableHead>
                  <TableHead className="w-24 text-right">Rate</TableHead>
                  <TableHead className="w-20 text-right">Disc %</TableHead>
                  <TableHead className="w-20 text-right">GST %</TableHead>
                  <TableHead className="w-28 text-right">Total</TableHead>
                  <TableHead className="w-10 pr-3" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {lines.map((line, index) => {
                  const product = products.find((p) => p.id === line.productVariantId);
                  const uom = uoms.find((u) => u.id === line.uomId);
                  return (
                    <React.Fragment key={line.key}>
                      <TableRow className="hover:bg-transparent">
                        <TableCell className="max-w-[240px] pl-4 align-top whitespace-normal">
                          <Select
                            value={line.productVariantId || undefined}
                            onValueChange={(v) => handleProductChange(line.key, v)}
                          >
                            <SelectTrigger size="sm">
                              <SelectValue placeholder="Select product" />
                            </SelectTrigger>
                            <SelectContent>
                              {products.map((p) => (
                                <SelectItem key={p.id} value={p.id}>
                                  {p.name} · {p.sku}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <span className="mt-1 block text-caption text-muted-foreground tabular">
                            {product ? `${product.sku} · ${uom?.code ?? product.uomCode}` : ""}
                          </span>
                          <Input
                            value={line.supplierSku}
                            onChange={(e) => updateLine(line.key, { supplierSku: e.target.value })}
                            placeholder="Supplier's SKU (optional)"
                            className="mt-1.5 h-7 text-[12px]"
                          />
                          {fieldError(index, "quantity") && (
                            <p className="mt-1 text-[11px] text-destructive">{fieldError(index, "quantity")}</p>
                          )}
                        </TableCell>
                        <TableCell className="align-top">
                          <Input
                            type="number"
                            min={0}
                            value={line.quantity}
                            disabled={!line.isAvailable}
                            onChange={(e) => updateLine(line.key, { quantity: Number(e.target.value) })}
                            className="h-8.5 text-right tabular"
                          />
                        </TableCell>
                        <TableCell className="align-top">
                          <Input
                            type="number"
                            min={0}
                            value={line.unitPrice}
                            disabled={!line.isAvailable}
                            onChange={(e) => updateLine(line.key, { unitPrice: Number(e.target.value) })}
                            className="h-8.5 text-right tabular"
                          />
                          {fieldError(index, "unitPrice") && (
                            <p className="mt-1 text-[11px] text-destructive">{fieldError(index, "unitPrice")}</p>
                          )}
                        </TableCell>
                        <TableCell className="align-top">
                          <Input
                            type="number"
                            min={0}
                            max={100}
                            value={line.discountPct}
                            disabled={!line.isAvailable}
                            onChange={(e) => updateLine(line.key, { discountPct: Number(e.target.value) })}
                            className="h-8.5 text-right tabular"
                          />
                        </TableCell>
                        <TableCell className="align-top">
                          <Input
                            type="number"
                            min={0}
                            value={line.gstRate}
                            disabled={!line.isAvailable}
                            onChange={(e) => updateLine(line.key, { gstRate: Number(e.target.value) })}
                            className="h-8.5 text-right tabular"
                          />
                        </TableCell>
                        <TableCell className="align-top text-right">
                          <span className="block pt-2 font-medium text-foreground tabular">
                            {line.isAvailable
                              ? formatMoney(
                                  computeLine({
                                    quantity: line.quantity,
                                    unitPrice: line.unitPrice,
                                    discountPct: line.discountPct,
                                    gstRate: line.gstRate,
                                    cessRate: 0,
                                  }).lineTotal,
                                )
                              : "—"}
                          </span>
                        </TableCell>
                        <TableCell className="pr-3 align-top">
                          <Button
                            variant="ghost"
                            size="icon-sm"
                            aria-label="Remove line"
                            className="mt-1 text-muted-foreground hover:text-destructive"
                            onClick={() => setLines((prev) => prev.filter((l) => l.key !== line.key))}
                          >
                            <Trash2 />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow className="hover:bg-transparent">
                        <TableCell colSpan={7} className="bg-muted/25 px-4 py-2">
                          <div className="flex flex-wrap items-center gap-2.5">
                            <Switch
                              id={`avail-${line.key}`}
                              checked={!line.isAvailable}
                              onCheckedChange={(checked) => updateLine(line.key, { isAvailable: !checked })}
                            />
                            <Label htmlFor={`avail-${line.key}`} className="text-[12.5px] font-normal">
                              Not available from this supplier
                            </Label>
                            {!line.isAvailable && (
                              <Input
                                value={line.availabilityNote}
                                onChange={(e) => updateLine(line.key, { availabilityNote: e.target.value })}
                                placeholder="Why? e.g. discontinued, out of stock..."
                                className="h-7 max-w-[320px] text-[12px]"
                              />
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    </React.Fragment>
                  );
                })}
              </TableBody>
            </Table>
            {create.fieldErrors.lines && (
              <p className="px-4 py-2 text-[12px] text-destructive">{create.fieldErrors.lines}</p>
            )}
          </SectionCard>
        </div>

        <div className="space-y-4 xl:col-span-4">
          <SectionCard title="Summary">
            <div className="space-y-3 p-4">
              <div className="space-y-1.5">
                <Label htmlFor="qf-freight">Freight</Label>
                <Input
                  id="qf-freight"
                  type="number"
                  min={0}
                  value={freightAmount}
                  onChange={(e) => setFreightAmount(Number(e.target.value))}
                  className="text-right tabular"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="qf-other">Other Charges</Label>
                <Input
                  id="qf-other"
                  type="number"
                  min={0}
                  value={otherCharges}
                  onChange={(e) => setOtherCharges(Number(e.target.value))}
                  className="text-right tabular"
                />
              </div>
              <TaxSummary money={totals} taxRows={taxRows} className="pt-1" />
            </div>
          </SectionCard>

          <div className="rounded-xl border border-border bg-card p-4">
            <p className="text-[12px] font-medium text-muted-foreground">Actions</p>
            <div className="mt-2.5 flex flex-col gap-2">
              <Button
                disabled={create.isPending || !quotationNumber.trim() || !supplierId}
                onClick={submit}
              >
                <Save />
                {create.isPending ? "Saving..." : "Save Quotation"}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
